name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  cache-zephyr-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Zephyr modules
        uses: actions/cache@v2
        with:
          path: /tmp/zmk-config/modules/
          key: ${{ runner.os }}-build-cache-zephyr-${{ hashFiles('**/zephyr/module.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-cache-zephyr-
          enableCrossOsArchive: false
          fail-on-cache-miss: true

  build:
    needs: cache-zephyr-modules
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    